baseURL = "https://daymunc.org/"
canonifyurls = "true"
languageCode = "en-us"
publishDir = "public"
sectionPagesMenu = "sidebar"
title = "DAYMUNC"
[params.carousel]
caption = ["", "", ""]
url = ["images/minified/ECOSOC.Voting.Fazekas.jpg", "images/minified/HABITAT.ResRevisions.Fazekas.jpg", "images/minified/ECOSOC.Award1.Fazekas.jpg"]
[params.variables]
committee_short = ["GA3", "PBC", "SC"]
daymunc_date = "Feb. 7-8, 2020"
numeral = "MMXX"
position_paper_deadline = "Friday, Jan. 26 at 11:59 pm"
sg_email = "secgen.daymunc@gmail.com"
webmaster_email = "matt.piekenbrock@gmail.com"
year = "2020"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
