baseURL = "https://daymunc.org/"
canonifyurls = "true"
languageCode = "en-us"
publishDir = "public"
sectionPagesMenu = "sidebar"
title = "DAYMUNC"
[params.carousel]
caption = ["", "", ""]
url = ["images/minified/ECOSOC.Voting.Fazekas.jpg", "images/minified/HABITAT.ResRevisions.Fazekas.jpg", "images/minified/ECOSOC.Award1.Fazekas.jpg"]
[params.variables]
committee_short = ["UNICEF", "CCPCJ", "SC", "SIMSEC"]
daymunc_date = "Feb. 1-2, 2019"
numeral = "XXV"
position_paper_deadline = "Friday, Jan. 26 at 11:59 pm"
sg_email = "secgen.daymunc@gmail.com"
webmaster_email = "matt.piekenbrock@gmail.com"
year = "2018"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
