baseURL = "/"
languageCode = "en-us"
publishDir = "public"
relativeURLs = "true"
canonifyurls = "true"
sectionPagesMenu = "sidebar"
title = "DAYMUNC"

[params.variables]
	numeral = "XXV"
	year = "2018"
	committee_short = ["UNDP", "UNICEF", "SC", "SIMSEC"]
	sg_email = "angelicamloyd@gmail.com"
	daymunc_date = "Jan. 5, 2018"
	webmaster_email = "matt.piekenbrock@gmail.com"

[params.carousel]
	caption = ["", "", ""]
	url = ["images/minified/ECOSOC.Voting.Fazekas.jpg", "images/minified/HABITAT.ResRevisions.Fazekas.jpg", "images/minified/ECOSOC.Award1.Fazekas.jpg"]
