baseURL = "http://example.org/"
languageCode = "en-us"
title = "Daymunc Site"
sectionPagesMenu = "sidebar"


[params.variables]
	numeral = "XXIII"
	year = "Thing"
	committee_short = ["UNICEF", "SC", "SIMSEC", "UNDP"]


