baseURL = "daymunc_website"
languageCode = "en-us"
title = "DAYMUNC"
sectionPagesMenu = "sidebar"
publishDir = "docs"

[params.variables]
	numeral = "XXV"
	year = "2018"
	committee_short = ["UNDP", "UNICEF", "SC", "SIMSEC"]
	sg_email = "angelicamloyd@gmail.com"
	daymunc_date = "Jan. 5, 2018"
	webmaster_email = "matt.piekenbrock@gmail.com"

[params.carousel]
	url = ["images/ECOSOC.Voting.Fazekas.jpg", "images/HABITAT.ResRevisions.Fazekas.jpg", "images/ECOSOC.Award1.Fazekas.jpg"]
	caption = ["", "", ""]

