baseURL = "https://daymunc.github.io/daymunc_website/"
canonifyurls = "true"
languageCode = "en-us"
publishDir = "public"
sectionPagesMenu = "sidebar"
title = "DAYMUNC"
[params.carousel]
caption = ["", "", ""]
url = ["images/minified/ECOSOC.Voting.Fazekas.jpg", "images/minified/HABITAT.ResRevisions.Fazekas.jpg", "images/minified/ECOSOC.Award1.Fazekas.jpg"]
[params.variables]
committee_short = ["UNDP", "UNICEF", "SC", "SIMSEC"]
daymunc_date = "Jan. 5, 2018"
numeral = "XXV"
sg_email = "angelicamloyd@gmail.com"
webmaster_email = "matt.piekenbrock@gmail.com"
year = "2018"
