---
label: default
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
pages:
- content/committees/UNEA.md
- content/committees/CSW.md
- content/apply-to-staff-at-daymunc.md
